### PR TITLE
Allow rotation of authorization secrets

### PR DESCRIPTION
**Pull request by neilmiddleton**

### CODE REVIEW

**Comment by neilmiddleton** [comment]
Is this OK to merge @jdxcode ?

**Comment by jdxcode** [comment]
@neilmiddleton is this intended to be sudo only?

**Comment by neilmiddleton** [comment]
No, I guess I didn't really think this would be public but it is.  I assume I just need to remove `+  needsAuth: true,
`?

**Comment by jdxcode** [comment]
that can stay in, but the command description has the word '(sudo)' in it

**Comment by neilmiddleton** [comment]
Good spot @jdxcode.  Removed.

**Comment by neilmiddleton** [comment]
can haz merge?

**Pull request merged**
